[phases.setup]
nixPkgs = ["python39", "nodejs-18_x"]

[phases.install]
cmds = [
    "npm install --prefix frontend",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "npm run build --prefix frontend"
]

[start]
cmd = "gunicorn backend.app:app --bind 0.0.0.0:$PORT"