[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && SECRET_KEY=railway-production-secret-key-2024 PYTHONIOENCODING=utf-8 python startup_debug.py"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"