[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && gunicorn minimal_app:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"