[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && SECRET_KEY=railway-production-secret-key-2024 PYTHONIOENCODING=utf-8 gunicorn -c gunicorn.conf.py wsgi_app:app"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"