[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python app_fixed.py"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"

# Persistent volume for database storage
[volumes]
data = "/data"

[build.env]
NIXPACKS_PYTHON_VERSION = "3.11"