[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn backend.app:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"