[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python -m gunicorn -c gunicorn.conf.py app_fixed:app"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"

[build.env]
NIXPACKS_PYTHON_VERSION = "3.11"