[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
startCommand = "gunicorn app:app -b 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120 --worker-class eventlet"