[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.nixpacks]
providers = ["python"]

[build.nixpacks.config]
PYTHON_VERSION = "3.10"

[deploy.port]
PORT = 8080