[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
startCommand = "python -m gunicorn --bind 0.0.0.0:5000 --workers 2 --timeout 120 --worker-class eventlet app:app"