[build]
builder = "nixpacks"
buildCommand = "cd backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && python app.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.nixpacks]
providers = ["python"]

[build.nixpacks.config]
PYTHON_VERSION = "3.10"

[variables]
PORT = "8080"
PYTHONPATH = "backend"