[build]
builder = "dockerfile"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10


[variables]
PORT = "8080"
PYTHONPATH = "/app"