[build]
builder = "nixpacks" 
# Force redeploy: companion system fixes applied

[deploy]
startCommand = "cd backend && python app.py"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Persistent volume for database storage
[volumes]
data = "/data"

[build.env]
NIXPACKS_PYTHON_VERSION = "3.11"
NIXPACKS_INSTALL_CMD = "pip install -r backend/requirements.txt"