#!/bin/bash
PORT=${PORT:-8080}
WEB_CONCURRENCY=${WEB_CONCURRENCY:-1}
WORKER_CLASS=${WORKER_CLASS:-sync}
GUNICORN_TIMEOUT=${GUNICORN_TIMEOUT:-300}
cd /app
exec gunicorn app:app --bind 0.0.0.0:$PORT --workers $WEB_CONCURRENCY --worker-class $WORKER_CLASS --timeout $GUNICORN_TIMEOUT