name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Test Python is working
      run: |
        python --version
        python -c "print('Hello from Python!')"
        python -c "import sys; print('Python path:', sys.executable)"

    - name: Test basic Python functionality
      run: |
        python -c "
        # Test basic functionality
        print('Testing basic Python...')
        
        # Test imports
        import os
        import sys
        import json
        
        # Test basic operations
        data = {'test': 'success', 'number': 42}
        json_str = json.dumps(data)
        parsed = json.loads(json_str)
        
        assert parsed['test'] == 'success'
        assert parsed['number'] == 42
        
        print('Basic Python test: PASSED')
        "

    - name: Test Flask installation
      run: |
        pip install flask
        python -c "
        import flask
        print('Flask version:', flask.__version__)
        print('Flask installation: PASSED')
        "

    - name: Test project structure
      run: |
        ls -la
        echo "--- Backend directory ---"
        ls -la backend/ 2>/dev/null || echo "Backend directory not found"
        echo "--- GitHub workflows ---"
        ls -la .github/workflows/ 2>/dev/null || echo "Workflows directory not found"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deployment Status
      run: |
        echo "✅ Tests completed successfully"
        echo "🚀 Ready for deployment"
        echo "Railway will handle automatic deployment"