name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_soulbridge
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements-dev.txt
    
    - name: Run linting
      run: |
        cd backend
        # Run black on Python files, excluding certain directories
        black --check --diff . --exclude="/(\.git|__pycache__|\.pytest_cache|migrations|\.venv)/"
        # Run flake8 with basic error checking
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=__pycache__,.git,.pytest_cache,migrations,.venv
    
    - name: Run tests
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_soulbridge
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SECRET_KEY: test-secret-key-for-ci
        TEST_MODE: true
      run: |
        cd backend
        # Create tests directory if it doesn't exist
        mkdir -p tests
        # Run tests if they exist, otherwise just run a basic Python syntax check
        if [ -d "tests" ] && [ "$(ls -A tests)" ]; then
          pytest tests/ -v --cov=. --cov-report=xml
        else
          echo "No tests found, running syntax check instead"
          python -m py_compile app.py
          echo "Syntax check passed"
        fi
    
    - name: Upload coverage to Codecov
      if: success()
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security scan
      uses: pypa/gh-action-pip-audit@v1.0.8
      with:
        inputs: backend/requirements.txt
        ignore-vulns: |
          # Add any known false positives here

  deploy-preview:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy PR Preview
      run: |
        echo "PR #${{ github.event.number }} preview would deploy here"
        echo "Preview URL: https://pr-${{ github.event.number }}.soulbridge-staging.railway.app"

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        if [ -z "$RAILWAY_TOKEN" ]; then
          echo "RAILWAY_TOKEN not set, skipping Railway deployment"
          exit 0
        fi
        npm install -g @railway/cli
        railway login --token $RAILWAY_TOKEN
        railway up --service backend
        
    - name: Deployment notification
      if: always()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      run: |
        if [ -z "$SLACK_WEBHOOK" ]; then
          echo "SLACK_WEBHOOK not set, skipping notification"
          exit 0
        fi
        echo "Would send Slack notification here"